#!/usr/bin/env bash

. ./share.sh

if ! tmux has-session -t "${session_name}" 2> /dev/null;
then
  echo "Tmux session '${session_name}' does not exist. Please launch it firstly."
  exit 1
fi

create_window() {
  tmux new-window -t "${session_name}:${1}"
}

kill_window() {
  tmux kill-window -t "${session_name}:${1}"
}

create_window
kill_window 1

while read command; do
  if ! [[ "$command" =~ ^\ *(#|$)  ]];
  then
    if [[ $command =~ ^sleep\ .*$ ]];
    then
      $command
    else
      if [[ $command =~ ( C-[a-z])$ ]];
      then
        tmux send-keys -t $session_name "${command%%${BASH_REMATCH}}" ${BASH_REMATCH}
      else
        tmux send-keys -t $session_name "${command}"
      fi
    fi
  fi
done < ./commands.bash
